### ISSUE TITLE
Uprobe Analysis: Setup ebpf uprobes

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#118]
# Developer Story
1. As a developer
2. I want to set a uprobe on a symbol
3. So that i can collect information about the function calls

# Acceptance criteria
- Set a uprobe and collect event data

# Definition of Done: 
- Code for Components has been written. 
- The code does comply to the naming conventions of the used programming language
Code has been completed
 - Unclear code parts are provided with a short comment, to explain what this part is supposed to do.
One of the following requirements are met: 
- Developers submit a screenshots of the finished feature as a comment to the related issue OR  Developers provide a short description on how to use the feature
- Feature has been reviewed by another team member
- Feature has been merged and closed

**Comment by der-whity** [comment]
@tamemo99 do your only want an uProbe for arbitrary symbols or for a specific one from the requirements doc? Please specify!

**Comment by alinawlo** [comment]
duplicates with #138
