### ISSUE TITLE
Scheduling of a seperate SD meeting

### ISSUE THREAD

**Issue by AnnaH3003** [amosproj/amos2024ws03-android-zero-instrumentation#12]
To avoid a lengthy written discussion on Discord, the software developers agree on a one-time additional meeting to reach some fundamental decisions regarding the tech stack.

**Comment by fhilgers** [comment]
@AnnaH3003 I think this is the wrong repository.

**Comment by AnnaH3003** [comment]
> [@AnnaH3003](https://github.com/AnnaH3003) I think this is the wrong repository.

Thanks, I didn't realize!
