### ISSUE TITLE
CI Rework

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#139]
# Developer Story
1. As a developer
2. I want to run CI when creating a PR
3. So that I know every part of the system works

# Acceptance Critera
1. Decrease CI times

#Context 
We have a lot of dependencies that are not installed on standard gitlab runners.
It would be interesting to see whether using a self hosted runner speeds up our builds.

**Comment by fhilgers** [comment]
Done in #53
