### ISSUE TITLE
scope(daemon) get information about android processes to list/find/search them (research)

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#20]
Edit by @fhilgers

# User Story
1. As a User
2. I want to show information about processes running on the system
3. So that I can decide for which application I want to set uprobes

# Acceptance criteria
- Getting a list of processes in the daemon

Follow up tickets for searching, filtering, ui, etc.

**Comment by der-whity** [comment]
`adb shell ps -A` returns all active processes. We could call that command via the library `std::process` in Rust.

@tamemo99 could you specify, if there are any restrictions to the processes (maybe only non-root or from a specific user)? Otherwise there would be probably 50-300 entries.

**Comment by tamemo99** [comment]
@der-whity I also don't know yet, as the IP still didn't provide the requirements. 
kindly think of this suggestion: maybe add a "drop-down" menu to show: 10 , 25, 50, 100 process at a time
I will also ask about this once the requirements are provided.

**Comment by fhilgers** [comment]
We should also rather use something like https://docs.rs/procfs/latest/procfs/process/index.html for getting processes than  calling external programs.

**Comment by luca-dot-sh** [comment]
For the UI, we can show installed apps and even their icons. However, so far, i only managed to do so for apps that are shown in the launcher using queryIntentActivities. (which is likely not sufficient as we want to allow the selection of headless apps as well)
