### ISSUE TITLE
scope(ui) find timeseries visualization library (research)

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#21]

**Comment by luca-dot-sh** [comment]
I found this list of charting libraries for Android:
https://github.com/lucasrafagnin/android-charts?tab=readme-ov-file

Additionally, i found 
https://github.com/codeandtheory/YCharts

I will try out the most popular ones, but i think waiting for exact requirements on which types of charts are required would improve decision making.

**Comment by tamemo99** [comment]
@luca-dot-sh Thanks for the input 💯 
hopefully, the exact requirements will be delivered asap

**Comment by luca-dot-sh** [comment]
I have created an example of a live updating counter visualization using Vico. Should i commit this for this issue or as part of #47?
This screen is lacking axis, buttons for changing the timeframe etc.

[vico_library.webm](https://github.com/user-attachments/assets/e4ea5776-bde2-4c2c-a9bc-4fdb0a9c7628)

**Comment by luca-dot-sh** [comment]
This is using YCharts, i personally found it easier to use and it has more variety in charts

[ycharts_library.webm](https://github.com/user-attachments/assets/7b676daf-b4e5-4451-ae0f-a078187ff99c)
