### ISSUE TITLE
Home Screen and Navigation Drawer

### ISSUE THREAD

**Issue by alinawlo** [amosproj/amos2024ws03-android-zero-instrumentation#43]
## User story
1. As a user
2. I want / need have a home screen and a navigation drawer for the app
3. So that I can navigate easily throught the app

## Acceptance criteria
* UI is looks clear and is user-friendly. (Not overcrowded and not empty)
* Navigate smoothly between tabs
->Tabs should be well "structured"  (f.e.: first tab shows ebpf programms and allows the selection
2nd displays charts according to my applied selection)

## Definition of done (DoD)
* All acceptance criteria were met
* Feature has been fully implemented

**Comment by luca-dot-sh** [comment]
I created these two alternatives for navigation. The first one is the suggested tab layout without a home screen.
The second one has a home screen that the user could navigate from and to. For example, if i click on configuration, i would have a back button to go back to the home screen and make my next selection. With the tab layout, i don't need a home screen as i can just use the tabs to navigate. 
Which one should i go for?

![image](https://github.com/user-attachments/assets/4ff31960-5421-49fe-95a9-7bff4cfb7db8)
![image](https://github.com/user-attachments/assets/19b9caf4-a24f-492e-b346-53638c3c4c14)

**Comment by luca-dot-sh** [comment]
Another alternative would be the sidebar drawer, but i have not implemented that one yet.

**Comment by alinawlo** [comment]
I found the second layout actually nicer.

**Comment by alinawlo** [comment]
> I created these two alternatives for navigation. The first one is the suggested tab layout without a home screen. The second one has a home screen that the user could navigate from and to. For example, if i click on configuration, i would have a back button to go back to the home screen and make my next selection. With the tab layout, i don't need a home screen as i can just use the tabs to navigate. Which one should i go for?

I would say go for the second one, it looks nicer.

**Comment by luca-dot-sh** [comment]
thanks for the feedback, i will update it tomorrow

**Comment by luca-dot-sh** [comment]
It looks like this now, i added the top bar to the homescreen as well as fading it in and out did not look clean.
Colors are the default material design colors, but we can change those as well if you want to.
https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors

[updated_home.webm](https://github.com/user-attachments/assets/c44746cb-3b9b-48b7-b742-e97b9a6ed483)
