### ISSUE TITLE
Display Installed Applications in UI

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#73]
As a developer I want to:
Sketch a basic UI layout that will allow users to have an overview about installed applications.

As a user:
I want to be able to view the installed applications

Acceptance Criteria:
UI displays a list of installed applications with package names and icons (Whenever this is applicable)

**Comment by Mr-Kanister** [comment]
Is this still correct? #72 got changed to retrieve running processes not installed apps. Does this issue need to be changed, too?

**Comment by luca-dot-sh** [comment]
I still think it would make sense to display the processes belonging to applications as applications and send the backend the respective PIDs to observe. For processes not belonging to applications like daemons, we can show them as single processes. I think this should simply be a 1:N mapping from package to processes.

I am currently looking into ways of retrieving the processes of an application. With adb, we can run 
`pm dump com.google.android.gms` and get a list of its processes there under process summary.

We can start with just processes as this is already implemented in the backend, but i think applications would make sense in the long run.

**Comment by Mr-Kanister** [comment]
We might also be able to map the processes to packages via `dumpsys activity --proto`. It's proto files are here: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/proto/android/server/activitymanagerservice.proto

**Comment by luca-dot-sh** [comment]
For now, this is implemented as a list of processes.
