### ISSUE TITLE
Create kprobe to Track Blocking vfs_write Call

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#88]
As a developer:
I want to attach kprobe to vfs_write function so that I can detect and log blocking behavior in file system writes.

Acceptance Criteria: 
Data Captured:
Collect key information:
Process ID (PID).
File descriptor.
Size of the write operation.
Timestamp.

Performance:
Ensure the kprobe has minimal system impact.

**Comment by der-whity** [comment]
Einen Filedeskriptor hat vfs_write nicht als Parameter. siehe  [doc](https://elixir.bootlin.com/linux/v6.1.112/source/include/linux/fs.h#L2274)
An die anderen Informationen bin ich gekommen.
