### ISSUE TITLE
bill of materials

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#9]

**Comment by fhilgers** [comment]
For all android and kotlin deps:

https://github.com/CycloneDX/cyclonedx-gradle-plugin

For all rust deps:

https://github.com/CycloneDX/cyclonedx-rust-cargo

For all tooling deps (nix):

https://github.com/nikstur/bombon


They all have the same format and cyclonedx is the status quo regarding sbom.

**Comment by luca-dot-sh** [comment]
As part of #7, CycloneDX was integrated into the basic frontend app.
